"""changed image size

Revision ID: b47a874eec48
Revises: c88ebf2e776d
Create Date: 2025-03-19 06:54:47.329840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b47a874eec48'
down_revision = 'c88ebf2e776d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=350),
               type_=sa.String(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=350),
               existing_nullable=False)

    # ### end Alembic commands ###
