"""added an image section

Revision ID: c88ebf2e776d
Revises: e5f5a84f0342
Create Date: 2025-03-19 02:44:53.496350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c88ebf2e776d'
down_revision = 'e5f5a84f0342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=350), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
