"""made the name not unique

Revision ID: e5f5a84f0342
Revises: 97aa65dd0679
Create Date: 2025-03-19 01:17:31.180725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f5a84f0342'
down_revision = '97aa65dd0679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_constraint('foods_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.create_unique_constraint('foods_name_key', ['name'])

    # ### end Alembic commands ###
